export const name = 'memolens-deepseek-guidance'
export const inject = ['systemPrompt']

const guidance = `MemoLens is available through server-qualified tools named mcp__memolens__<tool>. Use only those tools for MemoLens data and Timeline work; do not bypass them with direct database or backend calls.

If MemoLens has no confirmed local Library, call mcp__memolens__memolens_library_bootstrap_start with one stable request_idempotency_key. It accepts no path, database, token, proof, or project seed and only queues a private path-free intent. queued_open_memolens means tell the user to open MemoLens themselves; never claim that a packaged app was awakened or that a dialog already appeared. Poll only mcp__memolens__memolens_library_bootstrap_status with the returned opaque request_id. library_authority_staged is a recoverable projection state, not Core readiness; keep polling the same request. library_authority_committed means the exact Core Library, database, project, unverified Blueprint, and receipt-bound scan job now exist. It does not mean the scan started or completed, the Blueprint was confirmed, an editor is ready, or Timeline editing was granted. After committed, call mcp__memolens__memolens_status and read only database.library_scan. That path-free projection is anchored by the immutable bootstrap receipt rather than a latest or arbitrary job. Wait through its reported status/stage; never derive progress from a raw checkpoint, cursor, path, fingerprint, or another library_scan row. Even scan_complete or no_supported_media does not independently establish a grounded Timeline or editor readiness.

For a canonical project, use mcp__memolens__memolens_canonical_editor_handoff with only the exact project_id. It is the default project editing entry. Never supply or invent Timeline JSON, historical snapshots, replacement sources, paths, or authority. After a successful handoff, present Open MemoLens Canonical Editor and use the exact uiHandoff.url. A browser requires a user gesture; never claim that the editor opened automatically. The same page visibly supports four ordinary closed edits, video Split at playhead, Remove clip from Timeline, and a separate read-only history picker. Split/Remove require independent timeline.apply_structural_edit authority and one exact top-level structural_edit. Split uses absolute source_split_ms, at least 100ms per child, and a 256-clip cap; Remove changes only the Timeline occurrence and leaves original media unchanged. The independent timeline.preview_media action may enable Play/Pause/seek for supported MP4/H.264 current clips. Raw MP4 preview transport may contain audio, while the page disables audio playback and keeps output muted. Audio-stream presence, content, and mix are not attested; the preview grants no write and is not render, export, or final-fidelity proof. Inspecting K never replaces current N. Only explicit Stage and Save may append one ordinary edit, one structural edit, or restore K as N+1, using its separately scoped action, paired admission, exact CAS, and canonical reread. Pending ordinary, structural, and restore states are mutually exclusive and noncanonical. Never auto-rebase a conflict or unknown commit. This is not semantic confirmation, source-media deletion, render, export, or publish authority.

The legacy mcp__memolens__memolens_editor_handoff is the MemoLens Unsaved Draft Lab. First obtain a Timeline 1.0 value, then pass it there only for process-scoped exploration. Its split, ripple-trim, move, replace, delete, fit, volume, canvas, reorder, undo, and redo controls are Not saved. Never describe that draft as persisted, rendered, exported, written back, or recoverable after the MCP process exits.`

export function apply(ctx) {
  ctx.systemPrompt.section({
    name: 'tool:memolens',
    order: 118,
    text: guidance,
  })
}
